FROM ubuntu:latest

# Setup repositories for prereqs
#RUN echo "deb http://www.deb-multimedia.org jessie main non-free" >> /etc/apt/sources.list && \
    #apt-get -y update && \
    #apt-get -y --force-yes install deb-multimedia-keyring && \
    #apt-get -y update

RUN apt-get -y update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next && \
    apt-get -y update && \
    apt-get clean

RUN apt-get -y install \
    ffmpeg \
    git \
    golang \
    libcurl4-openssl-dev \
    libjpeg-dev \
    libssl-dev \
    motion \
    python-dev \
    python-pip \
    v4l-utils \
    wget && \
    apt-get clean


RUN pip install motioneye
ADD ./rclone /usr/local/bin/

# Create media config dirs. These need to be persistent to save configuration 
# and images/videos generated by motion processes.
RUN mkdir -p /etc/motioneye /var/lib/motioneye
VOLUME [ "/etc/motioneye", "/var/lib/motioneye" ]
EXPOSE 8765
CMD /usr/local/bin/meyectl startserver
