#!/bin/bash
ROOT_DIRECTORY=${1:-/var/lib/motioneye}
PUSH_LOCATION=${2:-${ROOT_DIRECTORY}/cameras}
LOCKFILE=/var/run/upload2drive.lock

# Create a lock file so two concurrent runs don't happen
lockup(){
    echo "Creating lockfile"
    touch ${LOCKFILE}
}

# Delete the lockfile and exit with a response code
cleanup(){
    echo "Cleaning up after myself"
    rm -f ${LOCKFILE}
    exit ${1}
}

trap "cleanup 0" SIGHUP SIGINT SIGTERM

# If a lockfile is in progress, do nothing
if [ -f ${LOCKFILE} ]; then
    exit 0
else
    pushd ${PUSH_LOCATION} || cleanup 1
    lockup
    drive push -no-prompt -ignore-conflict > /var/log/upload2google
    popd
    cleanup 0
fi
