#!/bin/bash
LOCAL_PATH=${1:-/var/lib/motioneye}
LOCKFILE=/var/run/upload2drive.lock

trap "rm $LOCKFILE; exit" SIGHUP SIGINT SIGTERM

if [ -f ${LOCKFILE} ]; then
    exit 0
elif [ -d ${LOCAL_PATH}/.gd ]; then
    touch ${LOCKFILE}
    pushd ${LOCAL_PATH}
    drive push -q
    rm -f ${LOCKFILE}
fi
